import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'Prem',
      email: 'admin@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'shubham',
      email: 'user@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: 'Iced Coffee',
      slug: 'iced-coffee',
      category: 'coffee',
      image: '/images/p1.jpg', // 679px × 829px
      price: 120,
      countInStock: 20,
      brand: 'Nescafe',
      rating: 4.5,
      numReviews: 10,
      description: 'Delicious in taste and healthy',
    },
    {
      name: 'Brewed Coffee',
      slug: 'brewed-coffee',
      category: 'coffee',
      image: '/images/p2.jpg',
      price: 250,
      countInStock: 20,
      brand: 'Starbucks',
      rating: 4.0,
      numReviews: 10,
      description: 'Delicious in taste and healthy',
    },
    {
      name: 'Black Coffee',
      slug: 'black-coffee',
      category: 'coffee',
      image: '/images/p3.jpg',
      price: 25,
      countInStock: 15,
      brand: 'Nescafe',
      rating: 4.5,
      numReviews: 14,
      description: 'Delicious in taste and healthy',
    },
    {
      name: 'Latte Coffee',
      slug: 'latte-coffee',
      category: 'coffee',
      image: '/images/p4.jpg',
      price: 65,
      countInStock: 5,
      brand: 'Bru',
      rating: 4.5,
      numReviews: 10,
      description: 'Delicious in taste and healthy',
    },

    {
      name: 'Mocha Coffee',
      slug: 'mocha-coffee',
      category: 'coffee',
      image: '/images/p5.jpg',
      price: 65,
      countInStock: 5,
      brand: 'Bru',
      rating: 4.5,
      numReviews: 10,
      description: 'Delicious in taste and healthy',
    },

    {
      name: 'Cappucino',
      slug: 'cappucino-coffee',
      category: 'coffee',
      image: '/images/p6.jpg',
      price: 65,
      countInStock: 5,
      brand: 'Rage coffee',
      rating: 4.5,
      numReviews: 10,
      description: 'Delicious in taste and healthy',
    },
    {
      name: 'Americano Coffee',
      slug: 'americano-coffee',
      category: 'coffee',
      image: '/images/p7.jpg',
      price: 65,
      countInStock: 5,
      brand: 'Bru',
      rating: 4.5,
      numReviews: 10,
      description: 'Delicious in taste and healthy',
    },
    {
      name: 'Expresso Coffee',
      slug: 'expresso-coffee',
      category: 'coffee',
      image: '/images/p8.jpg',
      price: 65,
      countInStock: 5,
      brand: 'Bru',
      rating: 4.5,
      numReviews: 10,
      description: 'Delicious in taste and healthy',
    },
  ],
};
export default data;
